name: Build and Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Download and Install Zola
      run: |
        curl -s -L https://github.com/getzola/zola/releases/download/v0.8.0/zola-v0.8.0-x86_64-unknown-linux-gnu.tar.gz | tar xvzf - -C $HOME
        echo "PATH=\$HOME/zola:\$PATH" >> $GITHUB_ENV

    - name: Build with Zola
      run: zola build

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Deploy to GitHub Pages
      run: |
        git config --global user.email "actions@github.com"
        git config --global user.name "GitHub Actions"
        sudo apt-get install python3-pip
        pip3 install ghp-import
        zola build
        ghp-import -n public
        git push -fq https://${{ secrets.GH_TOKEN }}@github.com/${{ github.repository }}.git gh-pages
